image: Visual Studio 2017

environment:
  host: x86_64-pc-windows-msvc
  matrix:
    - platform: x86_64
      target: x86_64-pc-windows-msvc
      channel: stable
    - platform: x86_64
      target: i686-pc-windows-msvc
      channel: stable
    - platform: i686
      target: x86_64-pc-windows-msvc
      channel: nightly

matrix:
  allow_failures:
    - channel: nightly

# Do not build branch with open Pull Requests (avoids double build)
skip_branch_with_pr: true

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -yv --default-toolchain %channel% --default-host %host%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%
    - ps: $Env:PKG_CONFIG_ALLOW_CROSS=1
    - rustc -vV
    - cargo -vV
    - rustup target add %target%
    - git submodule update --init

build_script:
    - cargo build --release --target=%target%

test_script:
    - cargo test --target=%target% --verbose

artifacts:
    - path: target\$(target)\release\algo.exe
      name: algorithmia-$(platform)
      type: zip

before_deploy:
    - mkdir staging
    - copy target\release\algo.exe staging
    - cd staging
    - 7z a ../algorithmia-%APPVEYOR_REPO_TAG_NAME%-%target%.zip *

deploy:
  description: 'Windows release'
  # All the zipped artifacts will be deployed
  artifact: /.*\.zip/
  # Regenerate this auth_token for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Then go to 'https://ci.appveyor.com/tools/encrypt' and enter the newly generated token.
  # - Enter the "encrypted value" below
  # Note: this is a personal access token generated by anowell
  auth_token:
    secure: BL7xegmBpa0f7zoyHOQQf/2nCjt3c5K4YYz3oOhtyhhyYjiOPqF3m90vdEzluCzM
  provider: GitHub
  # deploy when a new tag is pushed and only on the stable channel
  on:
    # channel to use to produce the release artifacts
    # NOTE make sure you only release *once* per target
    channel: stable
    APPVEYOR_REPO_TAG: true
